src/main/java/au/gov/nla/dlir/models/Work.java
@AaronCMuller @terenceingram field added to support addition of row index value.
=> DSCS-1085 add rowIndex field

src/main/java/au/gov/nla/dlir/models/Work.java
@terenceingram @AaronCMuller @JonathanShaw @bsingh-nla
=> ms1051: add a new flag

src/main/java/au/gov/nla/dlir/models/Page.java
=> [DSCS-447] Adding commentsExternal to Page

src/main/java/au/gov/nla/dlir/models/Work.java
@scoen @terenceingram 
Add a new field: interactiveIndex
=> ms1105: add interactive index

src/main/java/au/gov/nla/dlir/models/RelatedDocs.java, src/main/java/au/gov/nla/dlir/models/RelatedDocument.java
@scoen can you please look.
renamed Transcripts.java to RelatedDocs.java
=> Bs dscs 539 rename

pom.xml, src/main/java/au/gov/nla/dlir/models/RelatedDocs.java
@scoen , @yetti , @MingtaoSun , @danielbaker can you please look.
=> Bs dscs 539 another rename

pom.xml, src/main/java/au/gov/nla/dlir/models/Acknowledgement.java, src/main/java/au/gov/nla/dlir/models/AcknowledgementList.java
@terenceingram, @scoen , @MingtaoSun, @danielbaker can you please look.
=> Bs dscs 106 ack

pom.xml, src/main/java/au/gov/nla/dlir/models/Transcripts.java
=> tarkine compile fix

pom.xml, src/main/java/au/gov/nla/dlir/models/Acknowledgement.java
@MingtaoSun , @danielbaker , @yetti can you please look.
=> data type changed

.gitignore, src/main/java/au/gov/nla/dlir/models/RelatedDocument.java
@scoen , @MingtaoSun , @danielbaker , @shuangzhou, @AaronCMuller can you please look.
=> related docs sorted by filename

src/main/java/au/gov/nla/dlir/models/Content.java
=> edition is a json Array

pom.xml, src/main/java/au/gov/nla/dlir/models/Content.java
@terenceingram , @MingtaoSun , @danielbaker , @yetti , @AaronCMuller can you please look.
=> deserialization bug fix

pom.xml, src/main/java/au/gov/nla/dlir/models/Work.java
@AaronCMuller @bsingh-nla @MingtaoSun
=> [DSCS-1306] DanB: adding sheetName and sheetCreationDate to work

src/main/java/au/gov/nla/dlir/models/Content.java, src/main/java/au/gov/nla/dlir/models/Work.java
adds the ebookType for discriminating between epubs and pdfs
=> Js ddg 103

pom.xml, src/main/java/au/gov/nla/dlir/models/RelatedDocument.java
@MingtaoSun , @danielbaker , @yetti , @scoen can you please look.
=> Bs dscs 1643 fas

src/main/java/au/gov/nla/dlir/models/Lookup.java, src/main/java/au/gov/nla/dlir/models/LookupList.java
@scoen , @danielbaker , @MingtaoSun , @yetti , @AaronCMuller can you please look.
=> added lookups pojo

pom.xml, src/main/java/au/gov/nla/dlir/models/map/MapIndex.java, src/main/java/au/gov/nla/dlir/models/map/Neighbour.java
@MingtaoSun , @terenceingram , @scoen , @danielbaker, @yetti  can you please look
=> map related metadata moved to pojo

src/main/java/au/gov/nla/dlir/models/Content.java
@scoen @yetti @MingtaoSun @josephcurtis
=> Remove unused fields that were causing issues.

src/main/java/au/gov/nla/dlir/models/Work.java
This change adds a method to Work to find whether it has a particular copy attached.
@JonathanShaw @MingtaoSun @shuangzhou
=> DSCS-2182: Added a method to Work to find whether it has a particular copy attached.

pom.xml, src/main/java/au/gov/nla/dlir/models/Work.java
Add expiry date to the Work Model. This field is now displayed in Tarkine and needs to be added to the model
@jrixon @yetti @sjacob @ninhnguyen @shuangzhou @weijunnla @scoen @nlahuwgeddes
=> Hg ddg 336 new title page

src/main/java/au/gov/nla/dlir/models/Work.java
Don't hard code access conditions on the work object.
@jrixon @scoen @ninhnguyen @m-r-c @weijunnla @shuangzhou @sjacob @adityaburra
=> Do not set default access condtions on the work object

src/main/java/au/gov/nla/dlir/models/Work.java
UAT changes.
@jrixon @scoen @ninhnguyen @m-r-c @weijunnla @shuangzhou @sjacob @adityaburra
=> Don't hard code access conditions on the work object.

pom.xml, src/main/java/au/gov/nla/dlir/models/PlaceOfPublication.java, src/main/java/au/gov/nla/dlir/models/Work.java
=> Mc nddn 652

pom.xml, src/main/java/au/gov/nla/dlir/models/Content.java, src/main/java/au/gov/nla/dlir/models/PlaceOfPublication.java, src/main/java/au/gov/nla/dlir/models/Work.java, src/main/java/au/gov/nla/dlir/models/bibdata/DataField.java, src/main/java/au/gov/nla/dlir/util/MarcDataHelper.java
=> UAT release for R18-7 

src/main/java/au/gov/nla/dlir/models/Content.java, src/main/java/au/gov/nla/dlir/util/MarcDataHelper.java
Things to consider before merging:
- Have you added unit tests for any new functionality?
- Do the unit tests run and pass?
- Have any dependencies already been merged?
- Has the documentation been updated?
- Has this change been added to a Release?
=> TOES-23 Added new fields for wikipedia citation

src/main/java/au/gov/nla/dlir/models/Work.java
Things to consider before merging:
- Have you added unit tests for any new functionality?
- Do the unit tests run and pass?
- Have any dependencies already been merged?
- Has the documentation been updated?
- Has this change been added to a Release?
=> TOES-49 Added new field 'allowSearchEngineIndexing'

Jenkinsfile, pom.xml, src/main/java/au/gov/nla/dlir/models/Parent.java, src/main/java/au/gov/nla/dlir/models/Work.java
=> feat(MDCU-492): Add a new field ocrMetsCopyAvaliable

src/main/java/au/gov/nla/dlir/models/CopyrightStatusResponse.java
Draft PR for the Copyright status language changes
=> 2021 copyight status revision

src/main/java/au/gov/nla/dlir/models/CopyrightStatusResponse.java
Hi Francis, 
Very quick wording adjustment requested by Rights Management. 
Look alright to you?
=> Removes 'Order a copy to the extent allowed under fair dealing' from copyright status responses.

src/main/java/au/gov/nla/dlir/models/CopyrightStatusResponse.java
Merging in of new wording for context messages in copyright status responses as requested by Rights Management.
=> Copyright2021 final wording

src/main/java/au/gov/nla/dlir/models/event/TextCorrectionMessage.java
Things to consider before merging:
- Have you added unit tests for any new functionality?
- Do the unit tests run and pass?
- Have any dependencies already been merged?
- Has the documentation been updated?
- Has this change been added to a Release?
=> Added rollback correction id field

Jenkinsfile, src/main/java/au/gov/nla/dlir/models/CopyrightStatusResponse.java, src/main/java/au/gov/nla/dlir/models/event/TextCorrectionMessage.java, src/test/java/au/gov/nla/dlir/models/event/TextCorrectionMessageTest.java, src/test/java/au/gov/nla/dlir/util/MarcDataHelperTest.java
Because it's reused in lots of places.
=> fix(MDCU-729): Move the logic of formatting correction lines here

src/main/java/au/gov/nla/dlir/models/Work.java
Things to consider before merging:
- Have you added unit tests for any new functionality?
- Do the unit tests run and pass?
- Have any dependencies already been merged?
- Has the documentation been updated?
- Has this change been added to a Release?
=> feat-tvit13-16): Associate images in DLC with a partner
